### ISSUE TITLE
DOMTimeStamp usage is not showing up

### ISSUE THREAD

**Issue by domenic** [dontcallmedom/webidlpedia#24]
https://dontcallmedom.github.io/webidlpedia/names/DOMTimeStamp.html does not show any usages of DOMTimeStamp

However, https://w3c.github.io/geolocation-api/ uses it.

It seems to be in webref: https://github.com/w3c/webref/blob/master/ed/idl/geolocation-API.idl

**Comment by dontcallmedom** [comment]
In reffy, we had opted [not to report dependencies on well-known types](https://github.com/w3c/reffy/blob/db0c76324f36757f20d52db85c75fb35fc7ac0e5/src/cli/parse-webidl.js#L352), by fear (if I remember correctly) that they would be too noisy; this is resulting in webidlpedia not showing the proper information. cc @tidoust

I could either make WebIDLpedia surface that lack of data for these types one way or another, or we could revisit the reffy decision. Your views on this would be much appreciated

(and sorry for the delay, the notifications for this repo were not correctly configured on my end)

**Comment by domenic** [comment]
Interesting! I can see how knowing every dependency on `DOMString` is not useful. Maybe just tweak the set? In particular DOMTimeStamp, Function, and VoidFunction are probably not referenced that much, and it'd be pretty interesting to see what APIs accept/return functions. Probably the binary data types would also be interesting.
