### ISSUE TITLE
Callback interfaces not listed

### ISSUE THREAD

**Issue by annevk** [dontcallmedom/webidlpedia#44]
I wanted to look into https://github.com/whatwg/webidl/issues/1282, but https://dontcallmedom.github.io/webidlpedia/names/ doesn't list `EventListener` anywhere.

(Amazing resource by the way, thanks for making it!)

**Comment by dontcallmedom** [comment]
they're there now, thanks for the report! https://dontcallmedom.github.io/webidlpedia/names/EventListener.html
